### ISSUE TITLE
Maven Mirror Overly Greedy

### ISSUE THREAD

**Issue by rs017991** [aegershman/pipeline-tasks#10] opened 2018-05-21 15:48 UTC
Trying to put all of the Maven Mirror/Cache stuff into my pipeline, and I've figured out why I had removed it in the first place:
The maven settings.xml claims that it is a mirror of * (everything), even though it's actually only a mirror of certain repositories. This causes dependencies to fail to load from other repositories, even when they are present in the POM.

https://github.com/aegershman/pipeline-tasks/blob/5c017f8722ccfc32227269655c955ad63755899f/maven/settings.xml#L14

**Comment by xyloman** [comment] 2018-05-21 16:23
We have to be careful here because long term the desire would be to have everything come from a single source of truth to ensure reproducability of builds if necessary.  If the dependencies pulled exist in a central nexus repository that value this gains is that everything is there.  But if this does not fit your purposes you can provide your own settings.xml via the MAVEN_CONFIG and point to your own settings.xml

**Comment by rs017991** [comment] 2018-05-22 15:35
What is the recommended location for such a file? The current one is in the pipeline-tasks repo

**Comment by rs017991** [comment] 2018-05-22 15:37
That is, in common.yml there is a dubious relative url that ends up in pipeline-tasks: `../pipeline-tasks/maven/settings.xml`

Relative to what? Unsure.

**Comment by aegershman** [comment] 2019-11-13 23:42
closing in preparation of archiving this repo

**Closed as completed by aegershman** 2019-11-13 23:42 UTC
